### ISSUE TITLE
Alert Module

### ISSUE THREAD

**Issue by ghost** [eTechSolutions/Hangfire#3]
Create an Alert Module for Hangfire to alert users of the following:
- [x] When there are no active servers.
- [x] When there is a spike in job failures.
- [x] Module system to register different notification types (e.g. email or new relic)

This functionality should link with New Relic so the internal IT can easily see all these alerts and possibly linking directly to email.

**Comment by quickskape** [comment]
After speaking with internal IT they would prefer an email rather than integrating with new relic. As this is simpler lets start there for now.
